# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env:
  SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
  TOKEN: ${{ secrets.TOKEN }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_SLUG: KhushrajRathod/TheOverseer

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 */1 * * *
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --frozen-lockfile
    - run: yarn start
    - run: wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - run: bash upload.sh 20.json results.json
